src/Entity/AllInclusiveTours.php
<?php

namespace App\Entity;

use App\Repository\AllInclusiveToursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AllInclusiveToursRepository::class)]
class AllInclusiveTours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 80)]
    private ?string $Hotel = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $Nights = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2)]
    private ?string $Price = null;

    #[ORM\Column(length: 10)]
    private ?string $Destination = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHotel(): ?string
    {
        return $this->Hotel;
    }

    public function setHotel(string $Hotel): self
    {
        $this->Hotel = $Hotel;

        return $this;
    }

    public function getNights(): ?int
    {
        return $this->Nights;
    }

    public function setNights(int $Nights): self
    {
        $this->Nights = $Nights;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->Price;
    }

    public function setPrice(string $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->Destination;
    }

    public function setDestination(string $Destination): self
    {
        $this->Destination = $Destination;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Controller/CreateController.php
<?php

namespace App\Controller;

use App\Entity\AllInclusiveTours;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;


class CreateController extends AbstractController
{
    #[Route('/create', name: 'app_create')]
    public function create(): Response
    {
        return $this->render('create/index.html.twig', [
            'controller_name' => 'CreateController',
        ]);
    }
}

src/Controller/ShowController.php
<?php

/*
$repository = $doctrine->getRepository(tour::class);
// query for a single tour by its primary key (usually "id")
$tour = $repository->find($id);
// dynamic method names to find a single tour based on a column value
$tour = $repository->findOneById($id);
$tour = $repository->findOneByName('Keyboard');
// dynamic method names to find a group of tours based on a column value
$tours = $repository->findByPrice(19);
// find *all* tours
$tours = $repository->findAll(); 
*/

namespace App\Controller;

use App\Entity\AllInclusiveTours;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;


class ShowController extends AbstractController
{
    #[Route('/show/{id}', name: 'show-tours')]
    public function showTours($id, ManagerRegistry $doctrine)
    {

        $tour = $doctrine
            ->getRepository(AllInclusiveTours::class)
            ->find($id);
        if (!$tour) {
            throw $this->createNotFoundException(
                'No tour found for id ' . $id
            );
        } else {
            return new Response('Details from the tour with id ' . $id . ", tour destination is " . $tour->getDestination() . " and it cost " . $tour->getPrice() . "€");
        }
    }

    #[Route('/home', name: 'home-page')]
    public function showToursInHome(ManagerRegistry $doctrine)
    {
        $tours = $doctrine
            ->getRepository(AllInclusiveTours::class)
            ->findAll(); // this variable $products will store the result of running a query to find all the products
        return $this->render('home.html.twig', array("tours" => $tours));
        //sends the variable that have all the products as an array of objects to the index.html.twig page
    }
}

src/Controller/TestController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    #[Route('/home', name: 'home')]
    public function index(): Response
    {
        return $this->render('home.html.twig', [
            'controller_name' => 'TestController',
        ]);
    }
}

src/Controller/ToursController.php
<?php

namespace App\Controller;

use App\Entity\AllInclusiveTours;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;


class ToursController extends AbstractController
{
    #[Route('/tours', name: 'tours')]
    public function showTours(ManagerRegistry $doctrine): Response
    {
        // you can fetch the ManagerRegistry via $doctrine()
        $em = $doctrine->getManager();
        $tour = new AllInclusiveTours(); // here we will create an object from our class AllInclusiveTours.
        $tour->setHotel('Another Test Hotel'); // in our Product class we have a set function for each column in our db
        $tour->setNights(7);
        $tour->setPrice(959.99);
        $tour->setDestination('California');
        $tour->setImage('https://media-cdn.tripadvisor.com/media/photo-s/16/1a/ea/54/hotel-presidente-4s.jpg');



        // tells Doctrine you want to (eventually) save the entry (no queries yet)
        $em->persist($tour);
        // actually executes the queries (i.e. the INSERT query)
        $em->flush();
        return new Response('Saved new product with id ' . $tour->getId());
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

templates/home.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Travel Agency - Using Twig{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" 
        crossorigin="anonymous">
    
        <link rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"> 
        {% endblock %}
    </head>
    <body>

        {% block body %}

        {{ include('include/navbar.html.twig') }}

        {% for tour in tours  %}
            <ul>
           <li>{{ tour.destination }}</li>
           <li>{{ tour.price }}</li>
            </ul>
        {% endfor %}

              
        {% endblock %}
                
        
        
        {% block javascripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
	    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" 
	    crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/include/navbar.html.twig
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="../home.html.twig">Travel Agency</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="../home.html.twig">Home</a>
        <a class="nav-link active" href="#">Features</a>
        <a class="nav-link active" href="#">Pricing</a>
        <a class="nav-link active" href="#">Disabled</a>
      </div>
    </div>
  </div>
</nav>

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ShowController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/isabe/OneDrive/Desktop/Symfony/Symfony_Twig/travel_agency/src/Controller/ShowController.php'|file_link(0) }}">src/Controller/ShowController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/isabe/OneDrive/Desktop/Symfony/Symfony_Twig/travel_agency/templates/show/index.html.twig'|file_link(0) }}">templates/show/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/tours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ToursController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/isabe/OneDrive/Desktop/Symfony/Symfony_Twig/travel_agency/src/Controller/ToursController.php'|file_link(0) }}">src/Controller/ToursController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/isabe/OneDrive/Desktop/Symfony/Symfony_Twig/travel_agency/templates/tours/index.html.twig'|file_link(0) }}">templates/tours/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}